# Generated by Django 5.0.3 on 2024-03-11 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('done', '-created_at')},
        ),
    ]
